name: unicorn_binance_rest_api

channels:
  - lucit
  - conda-forge
  - defaults

dependencies:
  - python>=3.7
  - certifi
  - colorama
  - cryptography
  - cython
  - dateparser
  - lucit::lucit-licensing-python
  - importlib-metadata  # [py<38]
  - pyopenssl
  - pysocks
  - requests
  - regex
  - ujson
  - pip:
    - service-identity
    - requests[socks]
