name: unicorn_binance_rest_api

channels:
  - lucit
  - conda-forge
  - defaults

dependencies:
  - python>=3.7
  - certifi
  - colorama
  - cryptography
  - cython
  - dateparser
  - lucit::lucit-licensing-python
  - pyopenssl
  - pysocks
  - requests
  - regex
  - service-identity
  - ujson
  - pip:
    - requests[socks]