name: unicorn_binance_rest_api

channels:
  - lucit
  - conda-forge
  - defaults

dependencies:
  - python>=3.7
  - certifi>=2023.7.22
  - colorama
  - cryptography>=42.0.4
  - cython
  - dateparser
  - lucit::lucit-licensing-python>=1.8.2
  - importlib-metadata  # [py<38]
  - pyopenssl
  - pysocks
  - requests>=2.31.0
  - regex
  - ujson
  - pip:
    - service-identity
