name: unicorn_binance_rest_api
dependencies:
- python>=3.6.1
- pip:
  - certifi
  - colorama
  - cryptography
  - dateparser
  - pyOpenSSL
  - PySocks
  - requests
  - requests[socks]
  - regex
  - service-identity
  - ujson