name: unicorn_binance_rest_api
dependencies:
- python>=3.7
- pip:
  - certifi
  - colorama
  - cryptography
  - Cython
  - dateparser
  - lucit-licensing-python
  - pyOpenSSL
  - PySocks
  - requests
  - requests[socks]
  - regex
  - service-identity
  - ujson